@echo off
echo Cleaning up stale processes on ports 3000, 3001, 3002...
powershell -Command "Get-NetTCPConnection -LocalPort 3000,3001,3002 -ErrorAction SilentlyContinue | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue }"
powershell -Command "if (Test-Path 'apps\web\.next\dev\lock') { Remove-Item 'apps\web\.next\dev\lock' -Force }"
echo All clear! Starting dev servers...
yarn dev
